{
 "title": "Домашняя работа",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA1" },
    { "expr": "node_load5", "legendFormat": "CPULA5" },
    { "expr": "node_load15", "legendFormat": "CPULA15" }
   ]
  },
  {
   "title": "Память",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "Диск",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=\"ext4\"}"
    }
   ]
  }
 ]
}